"""init with cascade

Revision ID: 06256f26ff37
Revises:
Create Date: 2026-04-14 21:57:02.146050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06256f26ff37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Создаем enum типы с проверкой IF NOT EXISTS (PostgreSQL не поддерживает CREATE TYPE IF NOT EXISTS напрямую)
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'themetype') THEN
            CREATE TYPE themetype AS ENUM ('light', 'dark');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gender') THEN
            CREATE TYPE gender AS ENUM ('male', 'female');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'invitationstatus') THEN
            CREATE TYPE invitationstatus AS ENUM ('invited', 'accepted', 'declined');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'invitationtype') THEN
            CREATE TYPE invitationtype AS ENUM ('claim_member', 'new_member');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'relationshiptype') THEN
            CREATE TYPE relationshiptype AS ENUM ('son', 'daughter', 'mother', 'father', 'spouse', 'partner', 'brother', 'sister');
        END IF;
    END$$;
    """)

    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Таблица user
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('is_verified', sa.Boolean(), nullable=False),
        sa.Column('theme', postgresql.ENUM('light', 'dark', name='themetype', create_type=False), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_is_verified'), 'user', ['is_verified'], unique=False)

    # 2. Таблица family
    op.create_table('family',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('admin_user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['admin_user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # 3. Таблица event
    op.create_table('event',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('family_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_by_user_id', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['family_id'], ['family.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # 4. Таблица family_member
    op.create_table('family_member',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('is_admin', sa.Boolean(), nullable=False),
        sa.Column('family_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('first_name', sa.String(), nullable=False),
        sa.Column('last_name', sa.String(), nullable=False),
        sa.Column('patronymic', sa.String(), nullable=True),
        sa.Column('gender', postgresql.ENUM('male', 'female', name='gender', create_type=False), nullable=False),
        sa.Column('birth_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('death_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('workplace', sa.String(), nullable=True),
        sa.Column('residence', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_by_user_id', sa.Integer(), nullable=False),
        sa.Column('approved', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['family_id'], ['family.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_member_is_admin'), 'family_member', ['is_admin'], unique=False)

    # 5. Таблица album
    op.create_table('album',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('family_id', sa.Integer(), nullable=False),
        sa.Column('created_by_user_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=True),
        sa.Column('deletion_notified_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['family_id'], ['family.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_album_event_id', 'album', ['event_id'], unique=False)
    op.create_index('ix_album_expires_at', 'album', ['expires_at'], unique=False)
    op.create_index('ix_album_family_id', 'album', ['family_id'], unique=False)
    op.create_index('ix_album_is_deleted', 'album', ['is_deleted'], unique=False)

    # 6. Таблица chat
    op.create_table('chat',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('family_id', sa.Integer(), nullable=False),
        sa.Column('is_event', sa.Boolean(), nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=True),
        sa.Column('created_by_user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('title', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['family_id'], ['family.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_chat_is_event'), 'chat', ['is_event'], unique=False)

    # 7. Таблица event_participant
    op.create_table('event_participant',
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('status', postgresql.ENUM('invited', 'accepted', 'declined', name='invitationstatus', create_type=False), nullable=True),
        sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('event_id', 'user_id')
    )

    # 8. Таблица invitation
    op.create_table('invitation',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=20), nullable=False),
        sa.Column('family_id', sa.Integer(), nullable=False),
        sa.Column('created_by_user_id', sa.Integer(), nullable=False),
        sa.Column('invitation_type', postgresql.ENUM('claim_member', 'new_member', name='invitationtype', create_type=False), nullable=False),
        sa.Column('target_member_id', sa.Integer(), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('used_by_user_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['family_id'], ['family.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['target_member_id'], ['family_member.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['used_by_user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitation_code'), 'invitation', ['code'], unique=True)

    # 9. Таблица relationship
    op.create_table('relationship',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('from_member_id', sa.Integer(), nullable=False),
        sa.Column('to_member_id', sa.Integer(), nullable=False),
        sa.Column('relationship_type', postgresql.ENUM('son', 'daughter', 'mother', 'father', 'spouse', 'partner', 'brother', 'sister', name='relationshiptype', create_type=False), nullable=False),
        sa.ForeignKeyConstraint(['from_member_id'], ['family_member.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['to_member_id'], ['family_member.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_relationship_from_member', 'relationship', ['from_member_id'], unique=False)
    op.create_index('ix_relationship_to_member', 'relationship', ['to_member_id'], unique=False)
    op.create_index('ix_relationship_type_from', 'relationship', ['relationship_type', 'from_member_id'], unique=False)

    # 10. Таблица album_member
    op.create_table('album_member',
        sa.Column('album_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('can_edit', sa.Boolean(), nullable=False),
        sa.Column('can_delete', sa.Boolean(), nullable=False),
        sa.Column('status', postgresql.ENUM('invited', 'accepted', 'declined', name='invitationstatus', create_type=False), nullable=True),
        sa.Column('added_by_user_id', sa.Integer(), nullable=False),
        sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['added_by_user_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['album_id'], ['album.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('album_id', 'user_id')
    )

    # 11. Таблица chat_member
    op.create_table('chat_member',
        sa.Column('chat_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('is_admin', sa.Boolean(), nullable=True),
        sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('status', postgresql.ENUM('invited', 'accepted', 'declined', name='invitationstatus', create_type=False), nullable=True),
        sa.Column('added_by_user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['added_by_user_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('chat_id', 'user_id')
    )

    # 12. Таблица message
    op.create_table('message',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('chat_id', sa.Integer(), nullable=False),
        sa.Column('sender_user_id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('is_edited', sa.Boolean(), nullable=True),
        sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['sender_user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # 13. Таблица photo
    op.create_table('photo',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('album_id', sa.Integer(), nullable=False),
        sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
        sa.Column('file_path', sa.String(), nullable=False),
        sa.Column('original_filename', sa.String(), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('mime_type', sa.String(), nullable=False),
        sa.Column('file_hash', sa.String(length=64), nullable=False),
        sa.Column('width', sa.Integer(), nullable=True),
        sa.Column('height', sa.Integer(), nullable=True),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['album_id'], ['album.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_photo_album_id', 'photo', ['album_id'], unique=False)
    op.create_index('ix_photo_file_hash', 'photo', ['file_hash'], unique=False)
    op.create_index('ix_photo_uploaded_by', 'photo', ['uploaded_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_photo_uploaded_by', table_name='photo')
    op.drop_index('ix_photo_file_hash', table_name='photo')
    op.drop_index('ix_photo_album_id', table_name='photo')
    op.drop_table('photo')
    op.drop_table('message')
    op.drop_table('chat_member')
    op.drop_table('album_member')
    op.drop_index('ix_relationship_type_from', table_name='relationship')
    op.drop_index('ix_relationship_to_member', table_name='relationship')
    op.drop_index('ix_relationship_from_member', table_name='relationship')
    op.drop_table('relationship')
    op.drop_index(op.f('ix_invitation_code'), table_name='invitation')
    op.drop_table('invitation')
    op.drop_table('event_participant')
    op.drop_index(op.f('ix_chat_is_event'), table_name='chat')
    op.drop_table('chat')
    op.drop_index('ix_album_is_deleted', table_name='album')
    op.drop_index('ix_album_family_id', table_name='album')
    op.drop_index('ix_album_expires_at', table_name='album')
    op.drop_index('ix_album_event_id', table_name='album')
    op.drop_table('album')
    op.drop_index(op.f('ix_family_member_is_admin'), table_name='family_member')
    op.drop_table('family_member')
    op.drop_table('event')
    op.drop_table('family')
    op.drop_index(op.f('ix_user_is_verified'), table_name='user')
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')

    # Удаляем enum типы
    op.execute("DROP TYPE IF EXISTS themetype")
    op.execute("DROP TYPE IF EXISTS gender")
    op.execute("DROP TYPE IF EXISTS invitationstatus")
    op.execute("DROP TYPE IF EXISTS invitationtype")
    op.execute("DROP TYPE IF EXISTS relationshiptype")
    # ### end Alembic commands ###