"""change family and family_member tables

Revision ID: 3599d2f80272
Revises: c01b970f6d49
Create Date: 2026-03-09 18:48:04.919076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3599d2f80272'
down_revision: Union[str, Sequence[str], None] = 'c01b970f6d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album_member', sa.Column('status', sa.Enum('invited', 'accepted', 'declined', name='invitationstatus'), nullable=True))
    op.add_column('family_member', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('relationship', 'relationship_type',
               existing_type=postgresql.ENUM('son', 'daughter', 'mother', 'father', 'spouse', 'partner', name='relationshiptype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('relationship', 'relationship_type',
               existing_type=postgresql.ENUM('son', 'daughter', 'mother', 'father', 'spouse', 'partner', name='relationshiptype'),
               nullable=False)
    op.drop_column('family_member', 'created_at')
    op.drop_column('album_member', 'status')
    # ### end Alembic commands ###
