"""add gender

Revision ID: ab94bbf88c3a
Revises: f9a518077402
Create Date: 2026-04-05 21:24:04.262636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab94bbf88c3a'
down_revision: Union[str, Sequence[str], None] = 'f9a518077402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE gender AS ENUM ('male', 'female')")

    op.add_column('family_member', sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False))
    op.alter_column('relationship', 'relationship_type',
               existing_type=postgresql.ENUM('son', 'daughter', 'mother', 'father', 'spouse', 'partner', name='relationshiptype'),
               nullable=False)
    op.create_index('ix_relationship_from_member', 'relationship', ['from_member_id'], unique=False)
    op.create_index(op.f('ix_relationship_from_member_id'), 'relationship', ['from_member_id'], unique=False)
    op.create_index(op.f('ix_relationship_relationship_type'), 'relationship', ['relationship_type'], unique=False)
    op.create_index('ix_relationship_to_member', 'relationship', ['to_member_id'], unique=False)
    op.create_index(op.f('ix_relationship_to_member_id'), 'relationship', ['to_member_id'], unique=False)
    op.create_index('ix_relationship_type_from', 'relationship', ['relationship_type', 'from_member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relationship_type_from', table_name='relationship')
    op.drop_index(op.f('ix_relationship_to_member_id'), table_name='relationship')
    op.drop_index('ix_relationship_to_member', table_name='relationship')
    op.drop_index(op.f('ix_relationship_relationship_type'), table_name='relationship')
    op.drop_index(op.f('ix_relationship_from_member_id'), table_name='relationship')
    op.drop_index('ix_relationship_from_member', table_name='relationship')
    op.alter_column('relationship', 'relationship_type',
               existing_type=postgresql.ENUM('son', 'daughter', 'mother', 'father', 'spouse', 'partner', name='relationshiptype'),
               nullable=True)
    op.drop_column('family_member', 'gender')
    # ### end Alembic commands ###

    op.execute("DROP TYPE IF EXISTS gender")
