"""major_changes

Revision ID: f9a518077402
Revises: a6b81e4de0a8
Create Date: 2026-03-31 23:26:13.411716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9a518077402'
down_revision: Union[str, Sequence[str], None] = 'a6b81e4de0a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('description', sa.String(), nullable=True))
    op.add_column('album', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('album', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('album', sa.Column('deletion_notified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_album_event_id', 'album', ['event_id'], unique=False)
    op.create_index('ix_album_expires_at', 'album', ['expires_at'], unique=False)
    op.create_index('ix_album_family_id', 'album', ['family_id'], unique=False)
    op.create_index('ix_album_is_deleted', 'album', ['is_deleted'], unique=False)
    op.add_column('album_member', sa.Column('can_delete', sa.Boolean(), nullable=False))
    op.add_column('album_member', sa.Column('added_by_user_id', sa.Integer(), nullable=False))
    op.add_column('album_member', sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('album_member', 'can_edit',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'album_member', 'user', ['added_by_user_id'], ['id'])
    op.add_column('chat', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('chat', sa.Column('title', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'chat', ['event_id'])
    op.add_column('chat_member', sa.Column('added_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_member', 'user', ['added_by_user_id'], ['id'])
    op.add_column('event_participant', sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('event_participant', sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('message', sa.Column('is_edited', sa.Boolean(), nullable=True))
    op.add_column('message', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('photo', sa.Column('original_filename', sa.String(), nullable=False))
    op.add_column('photo', sa.Column('file_hash', sa.String(length=64), nullable=False))
    op.add_column('photo', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('photo', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('photo', sa.Column('description', sa.String(length=500), nullable=True))
    op.alter_column('photo', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('photo', 'mime_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_photo_album_id', 'photo', ['album_id'], unique=False)
    op.create_index('ix_photo_file_hash', 'photo', ['file_hash'], unique=False)
    op.create_index('ix_photo_uploaded_by', 'photo', ['uploaded_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_photo_uploaded_by', table_name='photo')
    op.drop_index('ix_photo_file_hash', table_name='photo')
    op.drop_index('ix_photo_album_id', table_name='photo')
    op.alter_column('photo', 'mime_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('photo', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('photo', 'description')
    op.drop_column('photo', 'height')
    op.drop_column('photo', 'width')
    op.drop_column('photo', 'file_hash')
    op.drop_column('photo', 'original_filename')
    op.drop_column('message', 'edited_at')
    op.drop_column('message', 'is_edited')
    op.drop_column('event_participant', 'responded_at')
    op.drop_column('event_participant', 'invited_at')
    op.drop_constraint(None, 'chat_member', type_='foreignkey')
    op.drop_column('chat_member', 'added_by_user_id')
    op.drop_constraint(None, 'chat', type_='unique')
    op.drop_column('chat', 'title')
    op.drop_column('chat', 'created_at')
    op.drop_constraint(None, 'album_member', type_='foreignkey')
    op.alter_column('album_member', 'can_edit',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('album_member', 'added_at')
    op.drop_column('album_member', 'added_by_user_id')
    op.drop_column('album_member', 'can_delete')
    op.drop_index('ix_album_is_deleted', table_name='album')
    op.drop_index('ix_album_family_id', table_name='album')
    op.drop_index('ix_album_expires_at', table_name='album')
    op.drop_index('ix_album_event_id', table_name='album')
    op.drop_column('album', 'deletion_notified_at')
    op.drop_column('album', 'is_deleted')
    op.drop_column('album', 'expires_at')
    op.drop_column('album', 'description')
    # ### end Alembic commands ###
